### ISSUE TITLE
Can't start the project

### ISSUE THREAD

**Issue by JerryGreen** [schettino/react-request-hook#13]
I wanted to play a bit with these [null/undefined](https://github.com/schettino/react-request-hook/issues/11), so I cloned the repo but after `yarn && yarn start` I've encountered two problems:

### First problem

```
rollup v0.66.6
bundles src/index.ts → dist/index.js, dist/index.es.js...
rpt2: options error TS5053 Option 'declaration' cannot be specified with option 'isolatedModules'.
created dist/index.js, dist/index.es.js in 2.7s

[2019-05-06 18:16:37] waiting for changes...
```

However, by "waiting for changes" I suppose it's working anyway...

### Second problem

I use the lib in my project - it's working ok. I managed to switch to my local `react-request-hook` with `yarn link` the lib, then `yarn link react-request-hook` in my project, but then I get this error in my app:

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

I tried to disable `declaration` and `isolatedModules` - it doesn't help, so it looks like these are different problems

### Just a note

Also, you use `allowSyntheticDefaultImports` and `esModuleInterop` at the same time - but `allowSyntheticDefaultImports` may be disabled ([here's why](https://github.com/Microsoft/TypeScript/pull/26866/commits/aaa723e2d2ee393331ac9d8eba29d66b80f415fe))

### Additional thoughts

I may miss something. Maybe it's good idea to place some "How to contribute" section in readme

**Comment by JerryGreen** [comment]
@schettino can you help with this? What am I missing?

**Comment by schettino** [comment]
I've seen this when there actually two versions of React being imported, but it happened in another library. Like, in the example folder, there's a CRA setup importing the library directly from NPM. Before, I was copying ([though a rollup plugin](https://github.com/schettino/react-request-hook/blob/e434801fd683a2b649c7cdb0a90e7ac35a2eedc4/rollup.config.js#L38)) the files to the example folder, so I could use the most recent build. 

The first warning you see is 'cause jest configure the option automatically and it was committed later on. #12 solves that. Thus, on the first problem, it generates the build just fine and as you used `start`, it will wait for changes to do the build again. The second problem is related to more than one React version in the same project. Let me dig into it to see if I can reproduce or, at least, have a minimal better setup. Thanks for raising that.

**Comment by JerryGreen** [comment]
@schettino I've made a minimal repo on top of `create-react-app`, check it out:

https://github.com/JerryGreen/react-request-hook-issue13

Just copy-paste the instructions from there, you'll see the error. May help you to start investigating

**Comment by schettino** [comment]
I've had a week off, looking into it today. Thanks Jerry!

**Comment by schettino** [comment]
@JerryGreen I looked into it and here's a quick summary: by doing `yarn link` (or npm) we end up with two react versions running side by side, one coming from CRA and another from the library's node_modules, which is expected somewhat. You can check that by running `npm ls react` (or react-dom). 

I ran your repo and faced the same problem. It's not specific to react-request-hook though. I did the same step by step with [this library ](https://github.com/facebookincubator/redux-react-hook) and got [this issue](https://github.com/facebook/react/issues/13991) which has the same [cause](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) as the ours.

Not too surprisedly, if you run `rm -rf node_modules` from the library folder it'll fix that. But it's not a good solution. There's also [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) and some other solutions suggested by the community. However, I do think we should have a straightforward working setup to iterate during development. So, for that, I'm going to revert our examples folder to use the files built locally and set up another repo with the same examples, that we can run through sandbox.

By the end, you'll be able to run `yarn install` followed by `yarn start`, which will listen for changes. From another terminal tab, `cd examples && yarn start` will use the latest build without having to link it. This for the development workflow. If you're testing on an actual project that uses CRA, the other approaches are still valid in this case. I haven't seen this happening before 'cause the projects I run for testing purposes don't use CRA, but I'm glad that you brought that up. Will put a PR asap. Thanks.
