### ISSUE TITLE
add an example with POST request?

### ISSUE THREAD

**Issue by JerryGreen** [schettino/react-request-hook#5]
How to pass params to the POST query?

**Comment by BrianMitchL** [comment]
You can pass in an Axios config  with the method being `post` and a data object. There are many helpful examples at the axios repo: https://github.com/axios/axios#axios-api
```js
const [item, postItem] = useResource((title, content) => ({
  url: `/item`,
  method: 'post',
  data: {
    title,
    content
  }
}));
```

**Comment by JerryGreen** [comment]
Cool

**Comment by ghost** [comment]
Don't want to open new issue, can't figure out how to add type for the `useResource` with POST request.

Let say we have such hook definition:
```typescript
const [, createPost] = useResource(
  ({ title, content, author }) => ({
    url: "/posts",
    method: "post",
    data: { title, content, author }
 })
);
```

I'd like to use next way:
```typescript
interface CreatePostRequest extends Request {
  // ???
}

const [, createPost] = useResource<CreatePostRequest>(/*...*/);
```

I've seen definition of the `Request` interface, but still can't figure out how to put `title`, `content` and `author` typed `string`. Any tips on how to work with `(...args: any[]): Resource<any>`?
Thanks in advance.
