### ISSUE TITLE
add typings/declaration to the lib?

### ISSUE THREAD

**Issue by JerryGreen** [schettino/react-request-hook#6]
I mean `.d.ts` files to get rid of the following error:

```
Could not find a declaration file for module 'react-request-hook'. '/client-2/node_modules/react-request-hook/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-request-hook` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-request-hook';`
```

**Comment by JerryGreen** [comment]
maybe it's a solution - https://github.com/schettino/react-request-hook/pull/4? (idk)

**Comment by schettino** [comment]
That's interesting, I haven't realized this as the examples I've worked didn't need it, for some reason. Will take a look and publish a patch with this. Thanks for the contribution.
