### ISSUE TITLE
Testing examples

### ISSUE THREAD

**Issue by BrianMitchL** [schettino/react-request-hook#8]
I'm trying to write some tests with react-testing-library and axios-mock-adapter, and am encountering the warning about the component updating inside a test that was not wrapped in `act(...)`. If anyone has any examples of how they were able to test components that use this library, that would be very helpful!

**Comment by petergledhill** [comment]
We have that problem too but it's actually a problem with React and the use of 'act'.  Looks like they've fixed it  react16.9.0-alpha.0, but I've yet to try it. https://github.com/facebook/react/issues/14769#issuecomment-479592338

**Comment by BrianMitchL** [comment]
Good call, my act warnings went away with `react@16.9.0-alpha.0`! Hope it's released soon 🤞

**Comment by schettino** [comment]
react@16.9.0-alpha.0 definitely solves this. There's a up [branch](https://github.com/schettino/react-request-hook/tree/act) where I upgrade the react version and update all tests to use the `act(async => ...`. I'm just waiting for the `alpha` be dropped though.
